// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBifeBidrPDdPvRhnxG5M7RcBswz_XCkYw',
    appId: '1:95296817485:web:ee00bf73704fdce5f78f04',
    messagingSenderId: '95296817485',
    projectId: 'spotifyappclone0101',
    authDomain: 'spotifyappclone0101.firebaseapp.com',
    storageBucket: 'spotifyappclone0101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1rSyYgSIpCiaYkDqldTTLQ4eYpFLTJZQ',
    appId: '1:95296817485:android:fa4f0fa7d01def93f78f04',
    messagingSenderId: '95296817485',
    projectId: 'spotifyappclone0101',
    storageBucket: 'spotifyappclone0101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQY_xCbj6EdCUiKT2VJS1T4cConDkSTF0',
    appId: '1:95296817485:ios:99f5cf578b5a28d9f78f04',
    messagingSenderId: '95296817485',
    projectId: 'spotifyappclone0101',
    storageBucket: 'spotifyappclone0101.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQY_xCbj6EdCUiKT2VJS1T4cConDkSTF0',
    appId: '1:95296817485:ios:99f5cf578b5a28d9f78f04',
    messagingSenderId: '95296817485',
    projectId: 'spotifyappclone0101',
    storageBucket: 'spotifyappclone0101.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBifeBidrPDdPvRhnxG5M7RcBswz_XCkYw',
    appId: '1:95296817485:web:976af8d6474ac685f78f04',
    messagingSenderId: '95296817485',
    projectId: 'spotifyappclone0101',
    authDomain: 'spotifyappclone0101.firebaseapp.com',
    storageBucket: 'spotifyappclone0101.appspot.com',
  );
}
